### ISSUE TITLE
Error after patching setup.py

### ISSUE THREAD

**Issue by lokkju** [lokkju/pyspatialite#12]
_From [uwe.seher](https://code.google.com/u/108699322544099468715/) on February 12, 2013 06:34:29_

What steps will reproduce the problem? 1. patch the original setup.py
2. run python setup.py install What is the expected output? What do you see instead? I expect a working module, i see the error below. 
I do it this way, because easy_install doesnt work with pyspatialite-3.0.1. 
Version pyspatialite 2.6.2-spatialite.2.4.0-4 installs without problems via easy_install. What version of the product are you using? On what operating system? pyspatialite-3.0.1, opensuse 12.1, python 2.7, libspatialite 3.0.1 or 4.0.0 Please provide any additional information below. (testenv)useher@deimos:~/devel/testenv/pyspatialite-3.0.1> patch -i fix_3.0.1_build_after_libspatialite_introduced_version_4.0.patch 
patching file setup.py
(testenv)useher@deimos:~/devel/testenv/pyspatialite-3.0.1> python setup.py install
running install
running build
running build_py
running build_ext
creating tmp
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -I/usr/include/python2.7 -c /tmp/iconvCfAzAD.c -o tmp/iconvCfAzAD.o
/tmp/iconvCfAzAD.c:1:1: warning: return type defaults to ‘int’ [-Wreturn-type]
/tmp/iconvCfAzAD.c: In function ‘main’:
/tmp/iconvCfAzAD.c:2:5: warning: implicit declaration of function ‘iconv’ [-Wimplicit-function-declaration]
/tmp/iconvCfAzAD.c:3:1: warning: control reaches end of non-void function [-Wreturn-type]
gcc -pthread tmp/iconvCfAzAD.o -L/usr/lib64 -o a.out
building 'pyspatialite._spatialite' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/amalgamation
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -DMODULE_NAME="spatialite.dbapi2" -DVERSION="3.0.1" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DOMIT_FREEXL=1 -I/Library/Frameworks/GEOS.framework/unix/include/ -I/Library/Frameworks/PROJ.framework/unix/include/ -Iamalgamation -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
In file included from src/module.c:24:0:
src/connection.h:36:5: error: conflicting types for ‘spatialite_init’
/usr/include/spatialite.h:82:29: note: previous declaration of ‘spatialite_init’ was here
error: command 'gcc' failed with exit status 1
(testenv)useher@deimos:~/devel/testenv/pyspatialite-3.0.1>

_Original issue: http://code.google.com/p/pyspatialite/issues/detail?id=12_
